Specie page
Natenadze/Collaboration pull request #1
Opened 2023-12-01 13:12 UTC by SesiliTs

2023-12-01 14:06 UTC, Natenadze requested changes
პატარა დეტალები მოვნიშნე და ნახე აბა.
მთავარი ფოტოების ნეთვორქინგია და დაგვააფდეითე მაგაზე აბა

2023-12-01 14:06 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +        tableView.reloadData()
ეს reloadData() main ზე უნდა გაუშვა Dispatch ით

2023-12-01 14:06 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Sesili/TableViewCell/SpecieTableViewCell.swift
> +    }
აქ არ იმუშავა ჩვენმა ფექიჯმა? URLSession ცალკე იდეალურ შემთხვევაში არ უნდა გვჭირდებოდეს

2023-12-01 14:44 UTC, Natenadze approved these changes
კარგია

2023-12-01 15:13 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +        tableView.reloadData()
p.s viewModel იდან ვაბრუნებთ main ზე პირდაპპირ და მაგიტო აღარაა აქ საჭირო დისპაჩი

2023-12-01 15:13 UTC, Natenadze approved these changes
ჩემგან მწვანე

2023-12-01 16:39 UTC, mmm11233 approved these changes

2023-12-01 16:45 UTC, TeklaMach approved these changes

2023-12-01 16:57 UTC, salomege commented
კარგი ნამუშევარია :)))

2023-12-01 17:09 UTC, salomege approved these changes

2023-12-01 17:52 UTC, merged

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +    var viewModel = SpecieViewModel()
private

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +    private let stackView = {
უფრო კონკრეტული დაარქვი მაგალითად
mainStackView

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +        view.backgroundColor = .white
ცალკე მეთოდში აჯობებდა

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +    private func addViews() {
addSubviews

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +            guard let self else { return }
ამის მერე self ები აღარ გჭირდება ქვედა ხაზებზე

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +            viewModel.fetchCity(cityName: cityName, tableView: tableView)
fetchCity ამის მაგივრად უფრო ზოგადი სახელის დარქმევა ჯობია
მაგალითად iinfoButtonDidTap

ანუ შენ მოდელს ის არუნდაუთხრა რომ რამე დაfetchოს არამედ უნდა უთხრა რომ ღილაკს დააკლიკეს

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieViewModel.swift
> +        let url = "https://api.inaturalist.org/v1/observations/species_counts?place_id=\(cityID[1])"
cityID[1] ამით მეორე ელემენტი ამოგაქვს და cityID.first ეს იქნებოდა მგონი სწორი

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +        viewModel.species.count
აჯობებს რომ ესე პირდაპირ არწვდებოდეს კონტროლერი viewModel ის propertyიებს და სერვის ქოლი რომ დაიქოლება დელეგატის მეთოდშ ბრუნდებოდეს მოდელი

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/SpecieController.swift
> +        self.leftView = paddingView
self არჭირდება წესით არც აქ არც ქვემოთ

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/TableViewCell/SpecieTableViewCell.swift
> +        prepareForReuse()
ამის დაძახება არაა საჭირო

2023-12-05 19:56 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Sesili/TableViewCell/SpecieTableViewCell.swift
> +extension UIImageView {
ცალკე ფაილში გაიტანე