Mariami
Natenadze/Collaboration pull request #2
Opened 2023-12-01 14:01 UTC by mmm11233

add pull request

2023-12-01 15:03 UTC, SesiliTs requested changes
დაგიწერე პატარა კომენტარები და გადახედე

2023-12-01 16:46 UTC, TeklaMach approved these changes
მარიამ, როგორც ნანა იტყოდა, სუპაა!

2023-12-01 17:13 UTC, SesiliTs approved these changes

2023-12-01 17:14 UTC, salomege approved these changes

2023-12-01 17:17 UTC, salomege approved these changes

2023-12-01 18:03 UTC, salomege approved these changes
Aproved

2023-12-01 18:08 UTC, salomege approved these changes

2023-12-01 18:08 UTC, Natenadze approved these changes
approve after conflicts resolved

2023-12-01 18:08 UTC, merged

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +    private let stackView: UIStackView = {
თუ არაფერს უსეტავ აქვე მაშნ ასე შექმენი  private let stackView = UIStackView()
ასევე ყველა ქვემოთ ჩამოთვლილიც

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +        viewModel.delegate = self
ცალკე მეთოდში

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +             viewModel.fetchWeather(lat: latitude, lon: longitude)
კოდის alignment არის არეული
ასევე ზოგადი დასახელება აჯობებდა. ესე გამოდის რომ კონტროლერი ეუბნება მოდელს რომ დაfetchოს რაღაც, რაც არასწორია. კონტროლერმა უნდა უთხრას რომ presentWeatherDidTap

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +        else {
ერთ ხაზზე დაწერე, აიტანე ეს მაღლა

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +        viewModel.fetchWeatherAccordingToCity(city: city)
same here as well

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +        if let temperature = viewModel.weather?.list.first?.main.temp {
viewModel ის propertyს რომ ესე პირდაპირ წვდები არასწორია რარაც მხრივ.
ასევე ლოგიკა გიწერია აქ რაც რეალურად viewModelს უნდა იყოს

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +    private func style() {
ძალიან დიდი მეთოდია, და დასაშლელია უეჭველად

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherController.swift
> +        stackView.setCustomSpacing(100, after: showWeatherButton)
ეგ ვაფშე არაა სტეკში ჩადებული :დ ამიტომ ეს ხაზი არიმუშავებდა :3

2023-12-05 20:19 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/ WeatherPage/WeatherControllerViewModel.swift
> +    func fetchWeather(lat: Double, lon: Double) {
ეს და ქვედა მეთოდი აჯობებს იყოს private