adding the pollution
Natenadze/Collaboration pull request #4
Opened 2023-12-01 15:58 UTC by TeklaMach

air quality check

2023-12-01 16:38 UTC, mmm11233 approved these changes

2023-12-01 16:58 UTC, SesiliTs requested changes

2023-12-01 16:58 UTC, SesiliTs commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +        viewModel.delegate = self
ეს ორი შეგიძლია addDelegate ფუნქციაში გაიტანო და ის ფუნქცია გამოიძახო დიდლოუდში

2023-12-01 18:19 UTC, Natenadze approved these changes
gud gud

2023-12-01 18:19 UTC, SesiliTs approved these changes

2023-12-01 18:20 UTC, salomege approved these changes

2023-12-01 19:34 UTC, merged

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/ViewModels/AirQualityModel.swift
> +    var airQuality: DataClass?
private

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/ViewModels/AirQualityModel.swift
> +                    if let airQuality{
airQuality ის მერე სფეისი

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +    let cityTextField: UITextField = {
ყველა property უნდა იყოს private

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +    var viewModel = AirQualityViewModel()
ესეც private

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +        view.backgroundColor = .white
ესენიც დაშალე ცალცალკე მეთოდებად
setupBackground
addSubviews
setupConstraints

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +            cityTextField.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 20),
ამეებს სტეკი აჯობებდა :3

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +        fetchButton.addTarget(self, action: #selector(fetchButtonTapped), for: .touchUpInside)
addAction

და ცალკე მეთოდში

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +            print("Please enter a city name")
წაშალე

2023-12-05 20:40 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Tekla/Views/AirQualityController.swift
> +    @objc func fetchButtonTapped() {
private