edit title
Natenadze/Collaboration pull request #5
Opened 2023-12-01 16:29 UTC by salomege

2023-12-01 16:38 UTC, mmm11233 approved these changes

2023-12-01 16:39 UTC, Natenadze requested changes
2 კომენტარი დაგიწერე და აბა შეხედე

2023-12-01 16:39 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/ViewModel/SolarResourceControllerViewModel.swift
> +class SolarResourceControllerViewModel {
მივაწეროთ final keyword კლასს

2023-12-01 16:39 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/ViewModel/SolarResourceControllerViewModel.swift
> +    }
დროში თუ არ გავიჭედებით, URLSession გვაქვს ამოსაცვლელი NatenWorking package ით.

2023-12-01 16:51 UTC, TeklaMach approved these changes

2023-12-01 17:06 UTC, SesiliTs approved these changes

2023-12-01 17:16 UTC, Natenadze approved these changes
კარგია

2023-12-01 18:12 UTC, merged

2023-12-05 20:33 UTC, Natenadze reviewed
comments before Nana <3 ))

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        textField.font = UIFont.systemFont(ofSize: 14)
აქ შეგვიძლია პირდაპირ  .systemFont(ofSize: 14)

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +    var viewModel = SolarResourceControllerViewModel()
private

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        submitButton.widthAnchor.constraint(equalToConstant: 100).isActive = true
ესენი ბარემ ზემოთ ერეიში ჩაყარე

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        )}
Enter

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +            UIAction(
ესენი 1 ხაზზე რო დატოვო უფრო მარტივი წასაკითხი იქნება

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        guard let address = addressTextField.text, !address.isEmpty
აქაც 1 ხაზი ჯობია და დაბლა ზედმეტი სფეისებია მოსაშორებელი

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        self.viewModel.fetchData(cityName: address) { [weak self] result in
self არ უნდა

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +            guard let self = self else { return }
guard let self else { return }

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +                self.updateUI(with: solarData.outputs)
აქ self აღარ უნდა, ზემოთ გარდში უკვე გვაქვს strong self

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        self.viewModel.fetchData(cityName: address) { [weak self] result in
fetch data ს შესახებ ჯობია არ იცოდეს კონტროლერმა და უბრალოდ გადასცე viewModel ს რო ღილაკს დაეჭირა, დანარჩენი თვითონ იცის და ის პასუხს დელეგატის საშუალებით გაგაგებინებს

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +final class SolarResourceController: UIViewController, UITextFieldDelegate {
UITextFieldDelegate ცალკე exstension ში გადაფარე და დაბლა ფუნქციებსაც გაიტან.

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +
// MARK: - Properties

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +            guard let self = self else { return }
დისპაჩში  [weak self] არ ვხმარობთ და დაბლაც აღარაა guard საჭირო

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/ViewModel/SolarResourceControllerViewModel.swift
> +import Foundation
ერთი მოვაშოროთ

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/ViewModel/SolarResourceControllerViewModel.swift
> +    func fetchData(cityName: String, completion: @escaping (Result<AddressResponse, Error>) -> Void) {
აქ ვეღარ მოვასწარით NatenWorking ნანა ))

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/ViewModel/SolarResourceControllerViewModel.swift
> +
// MARK: - Properties

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/ViewModel/SolarResourceControllerViewModel.swift
> +
// MARK: - Methods

2023-12-05 20:33 UTC, Natenadze commented on CollaborationTeamOne/Scenes/Salome/View/ViewModel/SolarResourceControllerViewModel.swift
> +                if let data = data {
if let data { საკმარისია

2023-12-05 20:53 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        stackView.distribution = .fill
დეფოლტადაა, წაშალე ეს ხაზი

2023-12-05 20:53 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +    var viewModel = SolarResourceControllerViewModel()
let

2023-12-05 20:53 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +            UIAction(
მე როგორც უწერია ეგრე უფრო მომწონს :დ

2023-12-05 20:53 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +                handler: { [weak self] action in
`handler: { [weak self] _ in`

2023-12-05 20:53 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +        self.viewModel.fetchData(cityName: address) { [weak self] result in
submitButtonDidTap ასე დარქმევა აჯობებდა

2023-12-05 20:53 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceController.swift
> +                print("Data fetched successfully")
წაშალე

2023-12-05 20:53 UTC, NanaJimsheleishvili commented on CollaborationTeamOne/Scenes/Salome/View/SolarResourceModel.swift
> +import Foundation
ეს ფაილი გამოგვრჩა
წასაშლელია